message = [1,2,'zhangsan',13.14,1,2,1]
message[2]='lisi'
print(type(message))
print(message[0])
print(message[2])
print(message.index(2))
print(message.index(13.14))
#print(message.index('wangwu'))
print(message.count('zhangsan'))
print(message.count(1))
print(message.count(2))
print(message.count('lisi'))
print(len(message))
print('zhangsan' in message)
print('lisi' in message)
print('zhangsan' not in message)
print('lisi' not in message)
message.append('yss')
print(message)
message1=['wangwu','zhaoliu']
message.append(message1)
print(message)
print(message[7])
message.extend('666666')
print(message)
message.extend(message1)
print(message)
message.insert(1,'maliu')
print(message)
message.insert(-1,'job')
print(message)
# del message1
# print(message1)
del message[3]
print(message)
tmp = message.pop(3)
print(tmp)
message.remove('yss')
print(message)
message.reverse()
print(message)
# message.sort(reverse=False)
# print(message)
message.sort(reverse=True)
print(message)
message1=message.copy()
print(message1)
i=0
while i<len(message):
    print(message[i],end='\t')
    i=i+1